### ISSUE TITLE
The AWS Access Key Id you provided does not exist in our records

### ISSUE THREAD

**Issue by barogo-jwyoon** [mafintosh/sqs#35]
i'm using sqs.

i try push with sqs npm.

follow code not working
```
...
const sqs = require('sqs')

const queue = sqs({
  access: ...,
  secret: ...,
  region: 'ap-northeast-2',
  https: true,
  proxy: '~/dispatch_req'
})

...

  queue.push('dispatch_req', {
    order_num: orderNum,
    st_map_x: stMapX
  }, () => {
    logger.info('finish')
  })

```

result

```
3|bapi     | Error: invalid status code from GetQueueUrl: 403. The AWS Access Key Id you provided does not exist in our records.dispatch_req
3|bapi     |     at Request._callback (/Users/jongwonyoon/barogo/barogo-api/node_modules/sqs/index.js:115:29)
3|bapi     |     at Request.self.callback (/Users/jongwonyoon/barogo/barogo-api/node_modules/sqs/node_modules/request/request.js:187:22)
3|bapi     |     at emitTwo (events.js:106:13)
3|bapi     |     at Request.emit (events.js:191:7)
3|bapi     |     at Request.<anonymous> (/Users/jongwonyoon/barogo/barogo-api/node_modules/sqs/node_modules/request/request.js:1048:10)
3|bapi     |     at emitOne (events.js:96:13)
3|bapi     |     at Request.emit (events.js:188:7)
3|bapi     |     at IncomingMessage.<anonymous> (/Users/jongwonyoon/barogo/barogo-api/node_modules/sqs/node_modules/request/request.js:969:12)
3|bapi     |     at emitNone (events.js:91:20)
3|bapi     |     at IncomingMessage.emit (events.js:185:7)
3|bapi     |     at endReadableNT (_stream_readable.js:974:12)
3|bapi     |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
3|bapi     |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

but follow code is working

```
const aws = require('aws-sdk')

aws.config.update({
  accessKeyId: ...,
  secretAccessKey: ...
})

const sqsAWS = new aws.SQS({region: 'ap-northeast-2'})

  sqsAWS.sendMessage({
    MessageBody: 'test_node1',
    QueueUrl: '~/dispatch_req'
  }, (err, data) => {
    if (err) {
      logger.error(err)
    }

    logger.info(data)
  })
```

acessKeyId and secretAccessKey is same.

i'm not find to sqs npm not working.

can help me....

thank you.

**Comment by trenskow** [comment]
I have the exact same issue.

**Comment by trenskow** [comment]
I've fixed it in this https://github.com/mafintosh/sqs/pull/36

**Comment by gyurobenjamin** [comment]
+1
